version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CODEBUILD_WEBHOOK_EVENT
      - echo $CODEBUILD_WEBHOOK_HEAD_REF
      - |
       if [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" && "$CODEBUILD_WEBHOOK_HEAD_REF" = "refs/heads/masterw"] ; then
           echo $CODEBUILD_WEBHOOK_EVENT
           echo sudheer
       fi
      - echo $CODEBUILD_WEBHOOK_TRIGGER
  post_build:
    commands:
      - echo Build completed on `date`